spring.application.name=DemoAi

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.max-output-tokens=500

#logging.level.org.springframework.ai.chat.client.advisor=DEBUG