spring.application.name=ToolCalling

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

app.weather.api-key=70eda467c1494dd992a151714250406