spring.application.name=AdvanceRag

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.options.model=gemini-embedding-001
spring.ai.vectorstore.mariadb.distance-type=COSINE
spring.ai.vectorstore.mariadb.dimensions=3072
spring.ai.vectorstore.mariadb.initialize-schema=true
#spring.ai.vectorstore.mariadb.remove-existing-vector-store-table=true


#spring.ai.google.genai.chat.options.max-output-tokens=500

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#db configurations
spring.datasource.url=jdbc:mariadb://localhost:3308/spring-ai
spring.datasource.username=root
spring.datasource.password=root

#spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS